import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * The uploaded PDFs themselves.
 *
 * The bundle record in lib/store holds measurements and extracted text — enough
 * to scrutinise, but not enough to REPAIR. Repagination, index rebuilding and
 * export all need the original bytes back, so they are written to disk under
 * uploads/<bundleId>/ and read again when a fix is requested.
 *
 * Disk rather than the database on purpose: a 90 MB paperbook has no business
 * in a Mongo document or in a process's memory, and the filesystem is the one
 * store that behaves the same whether or not Mongo is configured.
 *
 * uploads/ is gitignored. Nothing here is served statically — files are only
 * ever read back through an authenticated route that has already checked that
 * the bundle belongs to the caller.
 */

const ROOT = path.join(process.cwd(), "uploads");

/**
 * Ids are generated by us (`bnd_…`, `doc_…`), but this is the boundary between
 * an identifier and a filesystem path, so it is checked rather than trusted.
 */
function safeSegment(id: string): string {
  if (!/^[A-Za-z0-9_-]{1,64}$/.test(id))
    throw new Error(`unsafe path segment: ${id}`);
  return id;
}

const bundleDir = (bundleId: string) => path.join(ROOT, safeSegment(bundleId));

export async function saveDocumentFile(
  bundleId: string,
  documentId: string,
  bytes: Buffer
): Promise<void> {
  const dir = bundleDir(bundleId);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, `${safeSegment(documentId)}.pdf`), bytes);
}

/** Null when the file is gone — a restart on a machine where uploads/ was cleared. */
export async function readDocumentFile(
  bundleId: string,
  documentId: string
): Promise<Buffer | null> {
  try {
    return await readFile(
      path.join(bundleDir(bundleId), `${safeSegment(documentId)}.pdf`)
    );
  } catch {
    return null;
  }
}

export async function deleteBundleFiles(bundleId: string): Promise<void> {
  await rm(bundleDir(bundleId), { recursive: true, force: true });
}
