import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { GridFSBucket, type Db as MongoDb } from "mongodb";
import { getMongoDb } from "../mongodb";
import { usingMongo } from "../store";

/**
 * The uploaded PDFs themselves.
 *
 * The bundle record in lib/store holds measurements and extracted text, enough
 * to scrutinise but not enough to REPAIR. Repagination, index rebuilding,
 * sealing and export all need the original bytes back, so they are kept whole
 * and read again when a fix is requested.
 *
 * Two backends behind one interface, chosen the way lib/store chooses one:
 * GridFS when MONGODB_URI is set, the local filesystem otherwise.
 *
 * The filesystem is the better store where it exists. It costs nothing, it
 * streams, and a 90 MB paperbook has no business travelling through a database
 * driver. But it does not exist on a serverless host: the deployment is read
 * only apart from /tmp, and /tmp belongs to a single invocation on a single
 * instance, so a file written during upload is simply gone by the time sealing
 * asks for it. GridFS is the cheap way out, because it needs no second
 * account, no token and no new dependency. The Mongo the app already uses for
 * filings holds the bytes too, in 255 KB chunks, well clear of the 16 MB
 * document limit that rules out stashing a PDF in the bundle record.
 *
 * uploads/ is gitignored. Nothing here is served statically: files are only
 * ever read back through an authenticated route that has already checked the
 * bundle belongs to the caller.
 */

const ROOT = path.join(process.cwd(), "uploads");
const BUCKET = "uploads";

/**
 * Ids are generated by us (`bnd_…`, `doc_…`), but this is the boundary between
 * an identifier and a stored object, so it is checked rather than trusted.
 * GridFS names are built from the same checked segments, which keeps one id
 * rule for both backends instead of two that can drift apart.
 */
function safeSegment(id: string): string {
  if (!/^[A-Za-z0-9_-]{1,64}$/.test(id))
    throw new Error(`unsafe path segment: ${id}`);
  return id;
}

const bundleDir = (bundleId: string) => path.join(ROOT, safeSegment(bundleId));
const objectName = (bundleId: string, documentId: string) =>
  `${safeSegment(bundleId)}/${safeSegment(documentId)}.pdf`;

const bucket = (db: MongoDb) => new GridFSBucket(db, { bucketName: BUCKET });

export async function saveDocumentFile(
  bundleId: string,
  documentId: string,
  bytes: Buffer
): Promise<void> {
  if (!usingMongo()) {
    const dir = bundleDir(bundleId);
    await mkdir(dir, { recursive: true });
    await writeFile(path.join(dir, `${safeSegment(documentId)}.pdf`), bytes);
    return;
  }

  const db = await getMongoDb();
  const name = objectName(bundleId, documentId);

  // Saving the same document id twice replaces it. GridFS appends a revision
  // rather than overwriting, and a stale revision left behind would let the
  // seal cover bytes the advocate has already replaced.
  await deleteByName(db, name);

  await new Promise<void>((resolve, reject) => {
    const upload = bucket(db).openUploadStream(name, {
      metadata: { bundleId: safeSegment(bundleId), documentId: safeSegment(documentId) },
    });
    upload.on("error", reject);
    upload.on("finish", () => resolve());
    upload.end(bytes);
  });
}

/**
 * Null when the file is gone: a restart on a machine where uploads/ was
 * cleared, or a bundle record that outlived its bytes. Callers treat null as
 * "this document cannot be repaired" rather than as an error, because a
 * missing original is something to report to the advocate, not a crash.
 */
export async function readDocumentFile(
  bundleId: string,
  documentId: string
): Promise<Buffer | null> {
  if (!usingMongo()) {
    try {
      return await readFile(
        path.join(bundleDir(bundleId), `${safeSegment(documentId)}.pdf`)
      );
    } catch {
      return null;
    }
  }

  try {
    const db = await getMongoDb();
    const chunks: Buffer[] = [];
    for await (const chunk of bucket(db).openDownloadStreamByName(
      objectName(bundleId, documentId)
    )) {
      chunks.push(chunk as Buffer);
    }
    return Buffer.concat(chunks);
  } catch {
    return null;
  }
}

export async function deleteBundleFiles(bundleId: string): Promise<void> {
  if (!usingMongo()) {
    await rm(bundleDir(bundleId), { recursive: true, force: true });
    return;
  }

  const db = await getMongoDb();
  const files = await db
    .collection(`${BUCKET}.files`)
    .find({ "metadata.bundleId": safeSegment(bundleId) }, { projection: { _id: 1 } })
    .toArray();
  await Promise.all(files.map((f) => bucket(db).delete(f._id)));
}

/** Drop every revision stored under one name, ignoring a name that is not there. */
async function deleteByName(db: MongoDb, name: string): Promise<void> {
  const existing = await db
    .collection(`${BUCKET}.files`)
    .find({ filename: name }, { projection: { _id: 1 } })
    .toArray();
  await Promise.all(existing.map((f) => bucket(db).delete(f._id)));
}
