import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { GridFSBucket, type Db as MongoDb } from "mongodb";
import { getMongoDb } from "../mongodb";
import { usingMongo } from "../store";

/**
 * The uploaded PDFs, and the artifacts built from them.
 *
 * The bundle record in lib/store holds measurements and extracted text, enough
 * to scrutinise a filing but not enough to REPAIR one. Repagination, index
 * rebuilding, sealing and export all need the original bytes back, so they are
 * kept whole and read again when a fix is requested.
 *
 * Two backends behind one interface, chosen the way lib/store chooses one:
 * GridFS when MONGODB_URI is set, the local filesystem otherwise.
 *
 * The filesystem is the better store where it exists. It costs nothing, it
 * streams, and a 90 MB paperbook has no business travelling through a database
 * driver. But it does not exist on a serverless host: the deployment is read
 * only apart from /tmp, and /tmp belongs to a single invocation on a single
 * instance, so a file written during upload is simply gone by the time sealing
 * asks for it. GridFS is the cheap way out, because it needs no second
 * account, no token and no new dependency. The Mongo the app already uses for
 * filings holds the bytes too, in 255 KB chunks, well clear of the 16 MB
 * document limit that rules out stashing a PDF in the bundle record.
 *
 * uploads/ is gitignored. Nothing here is served statically: files are only
 * ever read back through an authenticated route that has already checked the
 * bundle belongs to the caller.
 */

const ROOT = path.join(process.cwd(), "uploads");
const BUCKET = "uploads";

/**
 * Ids are generated by us (`bnd_…`, `doc_…`), but this is the boundary between
 * an identifier and a stored object, so it is checked rather than trusted.
 * Both backends key off the same checked strings, so one rule governs them
 * instead of two that can drift apart.
 */
function safeSegment(id: string): string {
  if (!/^[A-Za-z0-9_.-]{1,120}$/.test(id) || id === "." || id === "..")
    throw new Error(`unsafe path segment: ${id}`);
  return id;
}

/** A key is one or two checked segments, e.g. "doc_x.pdf" or "artifact/final.json". */
const parts = (key: string) => key.split("/").map(safeSegment);

const bucket = (db: MongoDb) => new GridFSBucket(db, { bucketName: BUCKET });

async function put(bundleId: string, key: string, bytes: Buffer): Promise<void> {
  const segments = parts(key);

  if (!usingMongo()) {
    const dir = path.join(ROOT, safeSegment(bundleId), ...segments.slice(0, -1));
    await mkdir(dir, { recursive: true });
    await writeFile(path.join(dir, segments[segments.length - 1]), bytes);
    return;
  }

  const db = await getMongoDb();
  const name = `${safeSegment(bundleId)}/${segments.join("/")}`;

  // Storing the same key twice replaces it. GridFS appends a revision rather
  // than overwriting, and a stale revision left behind would let the seal
  // cover bytes that have already been replaced.
  await deleteByName(db, name);

  await new Promise<void>((resolve, reject) => {
    const upload = bucket(db).openUploadStream(name, {
      metadata: { bundleId: safeSegment(bundleId), key: segments.join("/") },
    });
    upload.on("error", reject);
    upload.on("finish", () => resolve());
    upload.end(bytes);
  });
}

/**
 * Null when it is not there: a restart on a machine where uploads/ was
 * cleared, a bundle record that outlived its bytes, or simply a cache miss.
 * Callers treat null as "cannot do this without the original" rather than as
 * an error, because a missing file is something to report to the advocate.
 */
async function get(bundleId: string, key: string): Promise<Buffer | null> {
  const segments = parts(key);

  if (!usingMongo()) {
    try {
      return await readFile(path.join(ROOT, safeSegment(bundleId), ...segments));
    } catch {
      return null;
    }
  }

  try {
    const db = await getMongoDb();
    const chunks: Buffer[] = [];
    for await (const chunk of bucket(db).openDownloadStreamByName(
      `${safeSegment(bundleId)}/${segments.join("/")}`
    )) {
      chunks.push(chunk as Buffer);
    }
    return Buffer.concat(chunks);
  } catch {
    return null;
  }
}

export const saveDocumentFile = (bundleId: string, documentId: string, bytes: Buffer) =>
  put(bundleId, `${documentId}.pdf`, bytes);

export const readDocumentFile = (bundleId: string, documentId: string) =>
  get(bundleId, `${documentId}.pdf`);

/**
 * Derived artifacts, as opposed to what the advocate uploaded.
 *
 * The assembled paperbook and its record are cached under a key derived from
 * the content that produced them. That cache is load-bearing rather than an
 * optimisation: the manifest records the moment of sealing, so rebuilding
 * instead of reading back would issue a different seal every time and the
 * certificate already downloaded would stop matching.
 *
 * Which is exactly why it cannot live on the local disk alone. A serverless
 * deployment has no writable one, and even a writable /tmp belongs to a single
 * instance, so two requests landing on two instances would disagree about what
 * had been sealed.
 */
export const saveArtifact = (bundleId: string, name: string, bytes: Buffer) =>
  put(bundleId, `artifact/${name}`, bytes);

export const readArtifact = (bundleId: string, name: string) =>
  get(bundleId, `artifact/${name}`);

export async function deleteBundleFiles(bundleId: string): Promise<void> {
  if (!usingMongo()) {
    await rm(path.join(ROOT, safeSegment(bundleId)), { recursive: true, force: true });
    return;
  }

  const db = await getMongoDb();
  const files = await db
    .collection(`${BUCKET}.files`)
    .find({ "metadata.bundleId": safeSegment(bundleId) }, { projection: { _id: 1 } })
    .toArray();
  await Promise.all(files.map((f) => bucket(db).delete(f._id)));
}

/** Drop every revision stored under one name, ignoring a name that is not there. */
async function deleteByName(db: MongoDb, name: string): Promise<void> {
  const existing = await db
    .collection(`${BUCKET}.files`)
    .find({ filename: name }, { projection: { _id: 1 } })
    .toArray();
  await Promise.all(existing.map((f) => bucket(db).delete(f._id)));
}
